fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    epel:
      repo: puppet/epel
    augeasproviders_core:
      repo: puppet/augeasproviders_core
    augeasproviders_shellvar:
      repo: puppet/augeasproviders_shellvar
    network:
      repo: puppet/network
    filemapper:
      repo: puppet/filemapper
    yum:
      repo: puppet/yum
  symlinks:
    infiniband: "#{source_dir}"
